## Shared goods-icon loader. Returns a Texture2D for a good at the right art TIER for the size it
## will be drawn at, or null if no icon exists yet. Most goods have no art, so callers must handle
## null.
##
## Three tiers on disk, smallest first:
##
##   very_small  ~256 px long edge, 5.9 MB total — thumbnails (list rows, chips, tick-lists)
##   small        450 px long edge,  13 MB total — THE WORKING TIER, and the default
##   medium      up to 2048 px,     208 MB total — master art, only for a display over 450 px
##
## 450 is not arbitrary: it is deposits_overlay.ICON_WORLD_ZOOMED_OUT, the largest size any good
## icon is drawn at anywhere in the game. `small` was generated by downscaling `medium` to that
## bound, so nothing on screen is ever short of pixels while `medium` — which is 16x the bytes for
## resolution nobody sees — stays out of the way. Nothing currently asks for a display over 450,
## so medium is effectively master art rather than runtime art.
##
## Icons are stored ready-to-display: any chroma-key background and watermark are baked out ahead
## of time (see tools/bake_good_icons.gd), and mipmaps are generated at import, so a tier drawn
## smaller than its native size is downsampled by the GPU rather than aliased.

const TIER_VERY_SMALL := "very_small"
const TIER_SMALL := "small"
const TIER_MEDIUM := "medium"

## Longest edge each tier supplies. A display larger than this steps up to the next tier;
## anything above the last entry gets medium.
const TIER_MAX_DISPLAY := {
	TIER_VERY_SMALL: 128.0,
	TIER_SMALL: 450.0,
}

const _TIER_DIR := {
	TIER_VERY_SMALL: "res://assets/icons/goods/very_small",
	TIER_SMALL: "res://assets/icons/goods/small",
	TIER_MEDIUM: "res://assets/icons/goods/medium",
}
## Search order per requested tier: the tier asked for, then bigger, then smaller. A good that
## exists in only one tier is still found — sharper than needed beats a blank icon, and blank is
## how a missing icon fails (every caller treats null as "draw nothing").
const _TIER_ORDER := {
	TIER_VERY_SMALL: [TIER_VERY_SMALL, TIER_SMALL, TIER_MEDIUM],
	TIER_SMALL: [TIER_SMALL, TIER_MEDIUM, TIER_VERY_SMALL],
	TIER_MEDIUM: [TIER_MEDIUM, TIER_SMALL, TIER_VERY_SMALL],
}
const _EXTS := [".png", ".svg", ".PNG", ".SVG"]

static var _texture_cache: Dictionary = {}


## The icon for a good at `tier`. Defaults to `small`, which covers every display in the game.
static func texture_for(good_id: String, internal_name: String, tier := TIER_SMALL) -> Texture2D:
	var cache_key := "%s|%s|%s" % [tier, good_id, internal_name]
	if _texture_cache.has(cache_key):
		return _texture_cache[cache_key] as Texture2D
	for dir in _dirs_for(tier):
		if good_id != "" and internal_name != "":
			var t := _try(dir, "%s_%s" % [good_id, internal_name])
			if t != null:
				_texture_cache[cache_key] = t
				return t
		if good_id != "":
			var t2 := _try(dir, good_id)
			if t2 != null:
				_texture_cache[cache_key] = t2
				return t2
		# Internal name alone, the way the building icons resolve. Art often lands before
		# the good has an id — or before it is in goods.csv at all — and naming the file
		# for the thing it draws means it starts working the moment the row exists,
		# instead of needing a rename nobody remembers to do.
		if internal_name != "":
			var t3 := _try(dir, internal_name)
			if t3 != null:
				_texture_cache[cache_key] = t3
				return t3
	_texture_cache[cache_key] = null
	return null


## The smallest tier whose art covers `display_size` px on its long edge.
static func tier_for_size(display_size: float) -> String:
	if display_size <= float(TIER_MAX_DISPLAY[TIER_VERY_SMALL]):
		return TIER_VERY_SMALL
	if display_size <= float(TIER_MAX_DISPLAY[TIER_SMALL]):
		return TIER_SMALL
	return TIER_MEDIUM


static func texture_for_size(good_id: String, internal_name: String, display_size: float) -> Texture2D:
	return texture_for(good_id, internal_name, tier_for_size(display_size))


static func _dirs_for(tier: String) -> Array:
	var order: Array = _TIER_ORDER.get(tier, _TIER_ORDER[TIER_SMALL])
	var out: Array = []
	for t in order:
		out.append(str(_TIER_DIR[t]))
	return out


static func _try(dir: String, stem: String) -> Texture2D:
	for ext in _EXTS:
		var path := "%s/%s%s" % [dir, stem, ext]
		if ResourceLoader.exists(path):
			return load(path) as Texture2D
	return null


## The on-disk path a texture_for(good_id, internal, tier) lookup resolves to, or "" if the good
## has no art. Same search order as texture_for so warming and drawing agree on which file each
## good uses.
static func resolve_path(good_id: String, internal_name: String, tier := TIER_SMALL) -> String:
	for dir in _dirs_for(tier):
		for stem in ([("%s_%s" % [good_id, internal_name]) if (good_id != "" and internal_name != "") else "", good_id, internal_name]):
			if stem == "":
				continue
			for ext in _EXTS:
				var path := "%s/%s%s" % [dir, stem, ext]
				if ResourceLoader.exists(path):
					return path
	return ""


## Kick off background (worker-thread) loads so icons are ready in the ResourceLoader cache before
## first use, in parallel with the map build rather than as a main-thread stall on first open.
## Warms `small`: it is what every surface draws, and warming medium instead pulled 208 MB of art
## nobody displays through the loader at startup.
static func warm_async(goods: Array, tier := TIER_SMALL) -> void:
	for g in goods:
		var path := resolve_path(str((g as Dictionary).get("id", "")),
			str((g as Dictionary).get("internal_name", "")), tier)
		if path != "":
			ResourceLoader.load_threaded_request(path)


## Populate _texture_cache for these goods (blocking, but fast once warm_async's worker loads have
## landed). Safe to call every load; a fully warmed run is a dictionary scan.
static func warm(goods: Array, tier := TIER_SMALL) -> void:
	for g in goods:
		texture_for(str((g as Dictionary).get("id", "")),
			str((g as Dictionary).get("internal_name", "")), tier)
