extends Node
# Per-turn power tracking + grid transaction settlement.
# Power is generated and consumed within the same PROCESS phase.
#
# Power flows over PHYSICAL cable networks: a network is a connected component of
# hex-adjacent cabled tiles. Generation on a tile covers that tile's own draw first,
# then the rest of its cable network; only the network's residual SURPLUS is sold to
# the national grid, and only its residual DEFICIT is bought — networks settle
# independently (a surplus network can sell while an isolated one buys).
# Cables on a tile are required for any power participation (production OR consumption).

var supply_this_turn: int = 0
var demand_this_turn: int = 0
# Per-tile power generated (export) and drawn (import) this turn — each hard-capped
# by the tile's cable level (see tile_power_cap). Reset each turn.
var tile_produced: Dictionary = {}
var tile_drawn: Dictionary = {}
# Of tile_produced, the portion generated by a building whose supply-priority
# category (MatchState.power_priority_coal_gas / _wind_solar) is currently set to
# "grid" — that generation always sells rather than covering local demand (owner,
# 28 Aug: coal/gas defaults to self-serving, wind/solar defaults to selling so
# local buildings draw firm grid power instead of exposure to its intermittency).
# Reset each turn alongside tile_produced.
var tile_produced_grid_priority: Dictionary = {}
# Per-tile attribution set during settlement: true when this tile's draw was fully
# covered by its own cable network's generation (own supply), false when any of it was
# imported from the national grid. Read by BuildingStatus.power_supply for the UI.
var _tile_self_supplied: Dictionary = {}
# Settled grid-import quantity per tile, shared by supply status and cost allocation.
var _tile_grid_draw: Dictionary = {}


# --- Battery storage (deposit model — docs/battery-storage-spec.md; moved from MatchState 2026-09-12). Saved under MatchState's "match" section via export_fields/import_fields; reset() is called by MatchState.reset(); tick_battery_fills() is driven from MatchState's PROCESS hook so firming capacity exists before production ---
## Battery cells loaded/unloaded on a tile changed (drives the tile-view power section + firming).
signal battery_cells_changed(tile_id: String)
# Battery cells loaded into a tile's battery housing (deposit model — locked, refundable capital,
# NOT consumed). {tile_id -> {good_id -> qty}}. Firming = min(housing slots, Σ cells × density).
var tile_battery_cells: Dictionary = {}
# In-flight battery fills awaiting delivery: [{tile_id, good_id, qty, turns_left}]. Paid/reserved
# at order time; the cells install into the housing when turns_left hits 0 (the "operational"
# countdown). Ticked once per turn at PROCESS start.
var pending_battery_fills: Array = []

func reset_for_turn() -> void:
	supply_this_turn = 0
	demand_this_turn = 0
	tile_produced.clear()
	tile_produced_grid_priority.clear()
	tile_drawn.clear()
	_tile_self_supplied.clear()
	_tile_grid_draw.clear()

func add_supply(amount: int) -> void:
	if amount > 0:
		supply_this_turn += amount

func add_demand(amount: int) -> void:
	if amount > 0:
		demand_this_turn += amount

# ── Per-tile cable power cap ────────────────────────────────────────────────
## A tile's per-turn power cap: cable-level cap (EconomyConfig.CABLE_POWER_CAP) × cable
## throughput research. 0 means no cables → no power production or draw.
func tile_power_cap(tile_id: String) -> int:
	var level := _tile_cable_level(tile_id)
	if level <= 0:
		return 0
	var cap := float(EconomyConfig.CABLE_POWER_CAP.get(level, 0))
	if cap <= 0.0:
		# Cable level above the table (e.g. a future L4 before the config is
		# extended): fall back to the highest defined cap, never a stale magic
		# number that would silently throttle the tile.
		cap = float(EconomyConfig.CABLE_POWER_CAP.values().max())
	return int(round(Modifiers.apply("transport_throughput", "cables", cap, {"mode": "cables"})))

## True if the tile can still produce `amount` more power this turn (export cap).
func can_produce(tile_id: String, amount: int) -> bool:
	return producible_amount(tile_id, amount) > 0 or amount <= 0

## How much of `amount` a generator on this tile may actually put on the wire this turn.
## PARTIAL DISPATCH (owner ruling 2026-07-27): a plant whose output slightly overshoots the
## tile's remaining cable headroom runs DERATED to fill the gap rather than idling — but only
## while the shortfall is under PARTIAL_DISPATCH_TOLERANCE of its own output. Past that it
## does not run at all, so a tile can't be packed with plants each contributing a sliver.
##   returns `amount` (fits) · the remaining headroom (small overshoot) · 0 (won't run)
## Before this, dispatch was all-or-nothing: two 690 MW plants filled 1380 of a 2000 cap and
## a third simply never started, stranding 620 MW of headroom while paying full upkeep.
const PARTIAL_DISPATCH_TOLERANCE: float = 0.25

func producible_amount(tile_id: String, amount: int) -> int:
	return dispatchable(amount, tile_power_cap(tile_id) - int(tile_produced.get(tile_id, 0)))

## The partial-dispatch decision on its own, free of tile lookups so it is directly testable:
## full output when it fits, the headroom when the overshoot is under the tolerance, else 0.
static func dispatchable(amount: int, headroom: int) -> int:
	if amount <= 0 or headroom <= 0:
		return 0
	if amount <= headroom:
		return amount
	if float(amount - headroom) < PARTIAL_DISPATCH_TOLERANCE * float(amount):
		return headroom
	return 0

## True if the tile can still draw `amount` more power this turn (import cap).
func can_draw(tile_id: String, amount: int) -> bool:
	if amount <= 0:
		return true
	return int(tile_drawn.get(tile_id, 0)) + amount <= tile_power_cap(tile_id)

## Record `amount` of power generated on a tile (counts toward its export cap + grid).
## `grid_priority` — this amount's building is currently set to sell to the grid
## rather than cover local demand (see tile_produced_grid_priority).
func record_produced(tile_id: String, amount: int, grid_priority: bool = false) -> void:
	if amount <= 0:
		return
	tile_produced[tile_id] = int(tile_produced.get(tile_id, 0)) + amount
	if grid_priority:
		tile_produced_grid_priority[tile_id] = int(tile_produced_grid_priority.get(tile_id, 0)) + amount
	add_supply(amount)

## Record `amount` of power drawn on a tile (counts toward its import cap + grid).
func record_drawn(tile_id: String, amount: int) -> void:
	if amount <= 0:
		return
	tile_drawn[tile_id] = int(tile_drawn.get(tile_id, 0)) + amount
	add_demand(amount)

## A tile's cable level (0 = uncabled). Public so the building-detail diagnostics can tell
## "upgrade your cables" from "this tile is already at the maximum".
func cable_level(tile_id: String) -> int:
	return _tile_cable_level(tile_id)

## True when this tile's cables are at the highest level the cap table defines — there is
## no upgrade left to suggest.
func cable_level_is_max(tile_id: String) -> bool:
	return _tile_cable_level(tile_id) >= EconomyConfig.CABLE_POWER_CAP.size()

func _tile_cable_level(tile_id: String) -> int:
	var hex_map = get_tree().get_first_node_in_group("hex_map") if get_tree() else null
	if hex_map == null:
		return 0
	var coord: Vector2i = hex_map.id_to_coord(tile_id)
	if coord == Vector2i(-1, -1):
		return 0
	var tile: Dictionary = hex_map.tiles.get(coord, {})
	if not tile.get("infrastructure_present", []).has("cables"):
		return 0
	return int(tile.get("infrastructure_levels", {}).get("cables", 1))

func is_supplied(tile_id: String, _energy_req: int = 0) -> bool:
	# A building can run as long as its tile has cables.
	# Power balance is settled at end of turn against the grid.
	# energy_req parameter kept for future use.
	if tile_id == "":
		return false
	return _tile_has_cables(tile_id)

func settle_grid_transactions() -> Dictionary:
	# Settle each cable network's residual net independently against the national grid, then
	# aggregate. A network is a connected component of adjacent cabled tiles; a surplus network
	# SELLS while a deficit network BUYS in the same turn (they don't cancel each other).
	_tile_self_supplied.clear()
	_tile_grid_draw.clear()
	var grid_bought: int = 0
	var grid_sold: int = 0
	var cabled := _cabled_tile_set()
	if cabled.is_empty():
		# No map / cable data available (headless unit context): single global pool
		# fallback — same self/grid-priority split as the per-network path below.
		# Strictly generalizes the old net_g formula: with no grid-priority
		# generation tagged, self_sum == supply_this_turn and this reduces to it.
		var grid_sum: int = 0
		for t in tile_produced_grid_priority:
			grid_sum += int(tile_produced_grid_priority[t])
		var self_sum: int = supply_this_turn - grid_sum
		var active_tiles := tile_produced.duplicate()
		active_tiles.merge(tile_drawn)
		_mark_network_supply(active_tiles.keys(), self_sum, demand_this_turn)
		var local_covered_g: int = mini(self_sum, demand_this_turn)
		var remaining_g: int = demand_this_turn - local_covered_g
		var surplus_g: int = self_sum - local_covered_g
		if remaining_g > 0:
			grid_bought = remaining_g
		var sold_g: int = surplus_g + grid_sum
		if sold_g > 0:
			grid_sold = sold_g
	else:
		# Seed a BFS from every tile with power activity; walk adjacent cabled tiles to build the
		# network, sum its generation vs demand, and settle only the residual with the grid.
		var active: Dictionary = {}
		for t in tile_produced:
			active[t] = true
		for t in tile_drawn:
			active[t] = true
		var seeds: Array = active.keys()
		seeds.sort()  # determinism
		var visited: Dictionary = {}
		for seed in seeds:
			if visited.has(seed):
				continue
			var comp: Array = _cable_component(str(seed), cabled, visited)
			# Split generation into what covers local demand ("self" priority) vs
			# what always sells ("grid" priority, e.g. wind/solar by default) —
			# supply-priority (owner, 28 Aug). Grid-priority generation never
			# counts toward covering this network's own demand, even if that
			# demand goes unmet; self-priority generation covers demand first,
			# and any of ITS surplus sells too, same as before this feature.
			var gen_self: int = 0
			var gen_grid: int = 0
			var dem: int = 0
			for t in comp:
				var produced: int = int(tile_produced.get(t, 0))
				var grid_share: int = int(tile_produced_grid_priority.get(t, 0))
				gen_grid += grid_share
				gen_self += produced - grid_share
				dem += int(tile_drawn.get(t, 0))
			var local_covered: int = mini(gen_self, dem)
			var remaining_dem: int = dem - local_covered
			var surplus_self: int = gen_self - local_covered
			if remaining_dem > 0:
				grid_bought += remaining_dem
			var sold: int = surplus_self + gen_grid
			if sold > 0:
				grid_sold += sold
			_mark_network_supply(comp, gen_self, dem)

	# A COO advisor negotiates grid tariffs: cheaper imported power (grid_buy_price)
	# and better-paid exports (grid_sell_price).
	var buy_mult: float = maxf(0.0, 1.0 + float(Modifiers.resolve_pct("grid_buy_price", "*", {}).get("net", 0.0)) / 100.0)
	var sell_mult: float = maxf(0.0, 1.0 + float(Modifiers.resolve_pct("grid_sell_price", "*", {}).get("net", 0.0)) / 100.0)
	return {
		"supply": supply_this_turn,
		"demand": demand_this_turn,
		"net": supply_this_turn - demand_this_turn,
		"grid_bought": grid_bought,
		"grid_sold": grid_sold,
		# Importing from the national grid carries the same carbon as generating the power
		# yourself would have. Without this the grid is the cleanest loophole on the board:
		# burn coal in your own plant and pay the levy, or buy the identical MW at a flat rate
		# and pay nothing. The grid is priced as if generated the conventional way, matching
		# how every other good's embodied carbon is derived.
		"grid_buy_cost": grid_bought * (EconomyConfig.GRID_BUY_PRICE * buy_mult
			+ MarketState.carbon_component(Catalog.get_good_by_internal_name("power").get("id", ""))),
		"grid_sell_revenue": grid_sold * EconomyConfig.GRID_SELL_PRICE * sell_mult,
	}

## True when this tile's power draw was fully covered by its own cable network's generation
## this turn (own supply); false when any of it was imported from the national grid.
func is_self_supplied(tile_id: String) -> bool:
	return bool(_tile_self_supplied.get(tile_id, false))

## Allocate the settled tile draw across its consumers. Owned power carries the
## export revenue forgone; imported power carries the actual tariff and carbon levy.
## Read after settle_grid_transactions(), so disconnected networks and grid-priority generation
## use exactly the same attribution as the power supply diagnostic.
func allocated_draw_cost(tile_id: String, amount: int) -> float:
	if amount <= 0:
		return 0.0
	var draw := int(tile_drawn.get(tile_id, 0))
	var imported_share := float(_tile_grid_draw.get(tile_id, draw)) / float(draw) if draw > 0 else 1.0
	var buy_mult := maxf(0.0, 1.0 + float(Modifiers.resolve_pct("grid_buy_price", "*", {}).get("net", 0.0)) / 100.0)
	var sell_mult := maxf(0.0, 1.0 + float(Modifiers.resolve_pct("grid_sell_price", "*", {}).get("net", 0.0)) / 100.0)
	var carbon := MarketState.carbon_component(str(Catalog.get_good_by_internal_name("power").get("id", "")))
	return float(amount) * ((1.0 - imported_share) * EconomyConfig.GRID_SELL_PRICE * sell_mult
		+ imported_share * (EconomyConfig.GRID_BUY_PRICE * buy_mult + carbon))

# --- Cable-network connectivity (physical adjacency) ---------------------------------------

# Every cabled tile_id on the map. Empty when no hex_map is present (pure headless context).
func _cabled_tile_set() -> Dictionary:
	var out: Dictionary = {}
	var hex_map = get_tree().get_first_node_in_group("hex_map") if get_tree() else null
	if hex_map == null:
		return out
	var tiles = hex_map.get("tiles")
	if tiles == null:
		return out
	for coord in tiles:
		var tile: Dictionary = tiles[coord]
		if (tile.get("infrastructure_present", []) as Array).has("cables"):
			out[_coord_to_id(coord)] = true
	return out

# Connected component of cabled tiles reachable from `seed` (flood-fill over hex adjacency).
func _cable_component(seed: String, cabled: Dictionary, visited: Dictionary) -> Array:
	var comp: Array = []
	var stack: Array = [seed]
	visited[seed] = true
	while not stack.is_empty():
		var t: String = str(stack.pop_back())
		comp.append(t)
		var c := _id_to_coord(t)
		if c == Vector2i(-1, -1):
			continue
		for nc in _neighbor_coords(c):
			var nid := _coord_to_id(nc)
			if cabled.has(nid) and not visited.has(nid):
				visited[nid] = true
				stack.append(nid)
	return comp

# Attribution: mark each tile own-supplied (draw covered by network generation) or grid.
# Same-tile generation covers same-tile draw first, then the network's residual generation
# pool covers the rest (deterministic tile order); any uncovered draw is a grid import.
func _mark_network_supply(comp: Array, gen: int, dem: int) -> void:
	if gen >= dem:
		for t in comp:
			_tile_self_supplied[t] = true  # network self-sufficient → every draw is own supply
			_tile_grid_draw[t] = 0
		return
	var pool: int = 0  # network residual generation after same-tile self-coverage
	var residual_dem: Dictionary = {}
	for t in comp:
		# Only SELF-priority generation counts toward "own supply" — grid-priority
		# generation (e.g. wind/solar sold to the grid by default) never covers a
		# draw directly, even on the same tile it was produced on.
		var g: int = int(tile_produced.get(t, 0)) - int(tile_produced_grid_priority.get(t, 0))
		var d: int = int(tile_drawn.get(t, 0))
		var self_cov: int = mini(g, d)
		pool += g - self_cov
		var rd: int = d - self_cov
		# Fully self-covered (or a pure generator / no draw) is own supply; residual decided below.
		_tile_grid_draw[t] = rd
		_tile_self_supplied[t] = rd == 0
		if rd > 0:
			residual_dem[t] = rd
	var order: Array = residual_dem.keys()
	order.sort()
	for t in order:
		var rd: int = int(residual_dem[t])
		var take: int = mini(rd, pool)
		pool -= take
		_tile_grid_draw[t] = rd - take
		_tile_self_supplied[t] = take >= rd  # fully covered by the network → own supply, else grid

# Hex (odd-q offset) neighbour coords — mirrors hex_map._neighbor_offset_for_hsm (pure).
func _neighbor_coords(c: Vector2i) -> Array:
	var odd: bool = c.x % 2 == 1
	return [
		c + Vector2i(0, -1),
		c + (Vector2i(1, 0) if odd else Vector2i(1, -1)),
		c + (Vector2i(1, 1) if odd else Vector2i(1, 0)),
		c + Vector2i(0, 1),
		c + (Vector2i(-1, 1) if odd else Vector2i(-1, 0)),
		c + (Vector2i(-1, 0) if odd else Vector2i(-1, -1)),
	]

func _coord_to_id(c: Vector2i) -> String:
	return "tile_%d_%d" % [c.x + 1, c.y + 1]

func _id_to_coord(t: String) -> Vector2i:
	var parts := t.split("_")
	if parts.size() != 3 or parts[0] != "tile":
		return Vector2i(-1, -1)
	if not parts[1].is_valid_int() or not parts[2].is_valid_int():
		return Vector2i(-1, -1)
	return Vector2i(int(parts[1]) - 1, int(parts[2]) - 1)

func _tile_has_cables(tile_id: String) -> bool:
	var hex_map = get_tree().get_first_node_in_group("hex_map")
	if hex_map == null:
		return false
	var coord: Vector2i = hex_map.id_to_coord(tile_id)
	if coord == Vector2i(-1, -1):
		return false
	var tile: Dictionary = hex_map.tiles.get(coord, {})
	return tile.get("infrastructure_present", []).has("cables")


## Match-scoped: cleared by MatchState.reset() (new game / scenario start).
func reset() -> void:
	tile_battery_cells.clear()
	pending_battery_fills.clear()


## Saved under MatchState's "match" section (keys unchanged from before the extraction).
func export_fields() -> Dictionary:
	return {
		"tile_battery_cells": tile_battery_cells.duplicate(true),
		"pending_battery_fills": pending_battery_fills.duplicate(true),
	}


func import_fields(d: Dictionary) -> void:
	tile_battery_cells = (d.get("tile_battery_cells", {}) as Dictionary).duplicate(true)
	pending_battery_fills = (d.get("pending_battery_fills", []) as Array).duplicate(true)


func get_tile_battery_cells(tile_id: String) -> Dictionary:
	return tile_battery_cells.get(tile_id, {})

# Total cell SLOTS the tile's player-owned battery housing provides (Σ cap by level).
func tile_battery_slots(tile_id: String) -> int:
	var slots := 0
	for inst in BuildingState.get_buildings_on_tile(tile_id):
		if not BuildingState.is_player_owned(inst):
			continue
		if str(Catalog.get_building(str(inst.get("building_id", ""))).get("category", "")) != "battery":
			continue
		slots += int(EconomyConfig.BATTERY_STORAGE_CAP.get(int(inst.get("level", 1)), 0))
	return slots

# Total cells loaded on the tile (across all battery types).
func tile_battery_cells_loaded(tile_id: String) -> int:
	var n := 0
	for q in get_tile_battery_cells(tile_id).values():
		n += int(q)
	return n

# Firming ⚡ the tile's loaded cells provide right now: Σ cells × density.
func tile_loaded_firming(tile_id: String) -> float:
	var f := 0.0
	var cells := get_tile_battery_cells(tile_id)
	for gid in cells:
		var internal := str(Catalog.get_good(str(gid)).get("internal_name", ""))
		f += float(cells[gid]) * float(EconomyConfig.BATTERY_CELL_DENSITY.get(internal, 0.0))
	return f

# Firming capacity a tile provides: loaded firming, capped at the housing's ⚡ capacity.
# (round, not floor — density is fractional, so e.g. 18 lithium cells = exactly 100 ⚡.)
func tile_firming_cap(tile_id: String) -> int:
	var slots := tile_battery_slots(tile_id)
	if slots <= 0:
		return 0
	return int(round(min(float(slots), tile_loaded_firming(tile_id))))

# Cells of `good_id` still needed to FILL the tile's remaining firming headroom.
# Pass `instance_id` to scope it to ONE battery instead: the panel is opened on a single
# building, and filling from the tile total meant a tile with four batteries ordered four
# batteries' worth from whichever one you happened to click. Cells are pooled
# per tile, so "this battery's share" is its own capacity less what the pool already firms —
# clamped to the tile's real remaining headroom so it can never over-order either.
func battery_cells_to_fill(tile_id: String, good_id: String, instance_id: String = "") -> int:
	var density := _battery_density(good_id)
	if density <= 0.0:
		return 0
	var loaded := tile_loaded_firming(tile_id)
	var free_firming := float(tile_battery_slots(tile_id)) - loaded
	if instance_id != "":
		var inst: Dictionary = BuildingState.get_building(instance_id)
		if not inst.is_empty():
			var own := float(EconomyConfig.BATTERY_STORAGE_CAP.get(int(inst.get("level", 1)), 0))
			free_firming = clampf(own - loaded, 0.0, free_firming)
	return maxi(0, int(floor(free_firming / density + 0.0001)))

func _battery_density(good_id: String) -> float:
	return float(EconomyConfig.BATTERY_CELL_DENSITY.get(
		str(Catalog.get_good(good_id).get("internal_name", "")), 0.0))

# A battery good is loadable only once its tech tier is unlocked.
func battery_type_loadable(good_id: String) -> bool:
	var internal := str(Catalog.get_good(good_id).get("internal_name", ""))
	if not EconomyConfig.BATTERY_TYPE_UNLOCK.has(internal):
		return false
	return ResearchState.is_unlocked(str(EconomyConfig.BATTERY_TYPE_UNLOCK[internal]))

# Load up to `qty` battery cells of `good_id` from the tile's stockpile into its housing
# (locked capital). Capped by the housing's free FIRMING headroom (cells × density must fit the
# ⚡ capacity), available stock, and tech unlock. Returns loaded count.
func load_battery_cells(tile_id: String, good_id: String, qty: int) -> int:
	if qty <= 0 or not battery_type_loadable(good_id):
		return 0
	var density := _battery_density(good_id)
	if density <= 0.0:
		return 0
	var free_firming := float(tile_battery_slots(tile_id)) - tile_loaded_firming(tile_id)
	var max_by_firming := int(floor(free_firming / density + 0.0001))  # epsilon: fractional density
	var avail := Stockpile.get_at_tile(tile_id, good_id)
	var take := mini(mini(qty, max_by_firming), avail)
	if take <= 0:
		return 0
	Stockpile.consume(tile_id, good_id, take)
	var cells: Dictionary = tile_battery_cells.get(tile_id, {})
	cells[good_id] = int(cells.get(good_id, 0)) + take
	tile_battery_cells[tile_id] = cells
	battery_cells_changed.emit(tile_id)
	return take

# Unload up to `qty` cells of `good_id` back to the tile stockpile (refund). Returns count.
func unload_battery_cells(tile_id: String, good_id: String, qty: int) -> int:
	if qty <= 0:
		return 0
	var cells: Dictionary = tile_battery_cells.get(tile_id, {})
	var have := int(cells.get(good_id, 0))
	var give := mini(qty, have)
	if give <= 0:
		return 0
	cells[good_id] = have - give
	if int(cells[good_id]) <= 0:
		cells.erase(good_id)
	if cells.is_empty():
		tile_battery_cells.erase(tile_id)
	else:
		tile_battery_cells[tile_id] = cells
	Stockpile.add(tile_id, good_id, give)
	battery_cells_changed.emit(tile_id)
	return give

# When housing shrinks (battery demolished / downgraded) and loaded firming exceeds the remaining
# ⚡ capacity, refund just enough cells to fit (stable type order).
func refund_battery_cells_over_slots(tile_id: String) -> void:
	var over_firming := tile_loaded_firming(tile_id) - float(tile_battery_slots(tile_id))
	if over_firming <= 0.0:
		return
	var cells: Dictionary = tile_battery_cells.get(tile_id, {})
	var gids: Array = cells.keys()
	gids.sort()
	for gid in gids:
		if over_firming <= 0.0:
			break
		var density := _battery_density(str(gid))
		if density <= 0.0:
			continue
		var give := mini(int(cells.get(gid, 0)), int(ceil(over_firming / density)))
		if give > 0:
			unload_battery_cells(tile_id, str(gid), give)
			over_firming -= float(give) * density

# Turns until the tile's in-flight fill completes (0 if none).
func battery_fill_turns_remaining(tile_id: String) -> int:
	var t := 0
	for f in pending_battery_fills:
		if str(f.get("tile_id", "")) == tile_id:
			t = maxi(t, int(f.get("turns_left", 0)))
	return t

# Order a fill from the MARKET: pay now; the cells install after the delivery lead. Returns
# {ok, turns, cost} (ok=false if not loadable / no route / can't afford).
func order_battery_fill_market(tile_id: String, good_id: String, qty: int) -> Dictionary:
	if qty <= 0 or not battery_type_loadable(good_id):
		return {"ok": false}
	var quote := TransportService.quote_market_buy(tile_id, good_id, qty, TransportState.seaport_would_cover(good_id))
	if quote.is_empty():
		return {"ok": false}
	var cost := float(quote.get("cost", 0.0))
	if not MatchState.deduct_money(cost):
		return {"ok": false, "reason": "funds", "cost": cost}
	TransportState.commit_sea_shipping(str(quote.get("port", "")), good_id, qty, "buy")
	var turns: int = maxi(1, int(quote.get("turns", 1)))
	pending_battery_fills.append({"tile_id": tile_id, "good_id": good_id, "qty": qty, "turns_left": turns})
	battery_cells_changed.emit(tile_id)
	return {"ok": true, "turns": turns, "cost": cost}

# Order a fill from ANOTHER TILE's stockpile: reserve the cells now; they install after the route
# time. Returns {ok, turns}.
func order_battery_fill_from_tile(tile_id: String, good_id: String, qty: int, source_tile: String) -> Dictionary:
	if qty <= 0 or not battery_type_loadable(good_id) or source_tile == "":
		return {"ok": false}
	if Stockpile.get_at_tile(source_tile, good_id) < qty:
		return {"ok": false, "reason": "stock"}
	var rt := TransportService.route(source_tile, tile_id, good_id)
	var turns: int = maxi(1, int(rt.get("turns", 1)))
	Stockpile.consume(source_tile, good_id, qty)  # reserve the cells for the journey
	pending_battery_fills.append({"tile_id": tile_id, "good_id": good_id, "qty": qty, "turns_left": turns})
	battery_cells_changed.emit(tile_id)
	return {"ok": true, "turns": turns}

# Tick all in-flight fills down a turn; install any that have arrived. (PROCESS start, so the
# new firming applies the same turn.)
func tick_battery_fills() -> void:
	if pending_battery_fills.is_empty():
		return
	var still: Array = []
	for f in pending_battery_fills:
		f["turns_left"] = int(f.get("turns_left", 0)) - 1
		if int(f["turns_left"]) > 0:
			still.append(f)
		else:
			_install_battery_cells(str(f.get("tile_id", "")), str(f.get("good_id", "")), int(f.get("qty", 0)))
	pending_battery_fills = still

# Install delivered cells straight into the housing (already paid/reserved — not from stockpile).
# Any that no longer fit (housing shrank in transit) fall back to the tile stockpile.
func _install_battery_cells(tile_id: String, good_id: String, qty: int) -> void:
	var density := _battery_density(good_id)
	if density <= 0.0 or qty <= 0:
		return
	var free_firming := float(tile_battery_slots(tile_id)) - tile_loaded_firming(tile_id)
	var take := mini(qty, maxi(0, int(floor(free_firming / density + 0.0001))))
	if take > 0:
		var cells: Dictionary = tile_battery_cells.get(tile_id, {})
		cells[good_id] = int(cells.get(good_id, 0)) + take
		tile_battery_cells[tile_id] = cells
	if qty - take > 0:
		Stockpile.add(tile_id, good_id, qty - take)
	battery_cells_changed.emit(tile_id)
