#!/usr/bin/env python3
"""Snapshot every balance-relevant number into ONE flat CSV, one row per recipe.

    python3 -B tools/snapshot_balancing.py [out.csv]

Written before the 2026-07-28 cost-reallocation pass so the pre-change economy can be
diffed against, or restored from, after the recipe formula is re-run. It reads the LIVE
data the game loads — data/recipes_all.csv, data/Goods - goodsMVP.csv,
data/Buildings - buildingsMVP.csv — plus the rate constants in scripts/economy_config.gd.

Why one wide table rather than the existing reports: the shipped balance reports are each
a slice (prices here, labour there, deployed cashflow elsewhere) and are regenerated by
tools that will themselves change. This is a single self-contained record — quantities,
prices, energy, labour and maintenance side by side, with the global rates repeated on
every row so the file stays interpretable when the constants move.

MAINTENANCE is a per-BUILDING number, so it is identical across every recipe sharing a
building; it is carried as a column per the owner's spec rather than split into a second
table, so one row is a complete costing.

LABOUR resolves the -1 compatibility sentinel: a recipe supplying its own head-counts wins,
otherwise the building's defaults apply. `labour_source` records which was used.
"""
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "reports/balance/temp_legacy_balancing.csv"

MAX_IN, MAX_OUT = 6, 5


def const(name: str, default: float) -> float:
    """Pull a float const out of economy_config.gd so the snapshot records the rates in force."""
    src = (ROOT / "scripts/economy_config.gd").read_text()
    m = re.search(r"const %s(?::\s*float)?\s*=\s*([\d.]+)" % re.escape(name), src)
    return float(m.group(1)) if m else default


RATE_U = const("LABOUR_UNSKILLED_RATE", 0.00304)
RATE_S = const("LABOUR_SKILLED_RATE", 0.00912)
RATE_H = const("LABOUR_HIGH_SKILLED_RATE", 0.0304)
GRID_BUY = const("GRID_BUY_PRICE", 0.12)

goods = {r["internal_name"]: r for r in csv.DictReader(open(ROOT / "data/Goods - goodsMVP.csv"))}
buildings = {r["internal_name"]: r for r in csv.DictReader(open(ROOT / "data/Buildings - buildingsMVP.csv"))}
recipes = list(csv.DictReader(open(ROOT / "data/recipes_all.csv")))


def price(internal: str) -> float:
    g = goods.get((internal or "").strip())
    if not g or not g.get("base_price"):
        return 0.0
    return float(g["base_price"])


def headcount(recipe: dict, building: dict, col: str) -> tuple:
    """(count, source) — the recipe's own figure, else the building's. -1/blank = fall back."""
    raw = (recipe.get(col) or "").strip()
    if raw not in ("", "-1"):
        try:
            return int(raw), "recipe"
        except ValueError:
            pass
    try:
        return int((building.get(col) or "0").strip() or 0), "building"
    except ValueError:
        return 0, "building"


cols = [
    "recipe_id", "display_name", "building_id", "building_display", "buildable", "category",
    "required_research", "catalysts",
    "maintenance_cost",
    "labour_unskilled", "labour_skilled", "labour_h_skilled", "labour_source",
    "energy_req",
]
for i in range(1, MAX_IN + 1):
    cols += ["input_%d" % i, "qty_%d" % i, "input_%d_price" % i]
for i in range(1, MAX_OUT + 1):
    cols += ["output_%d" % i, "output_qty_%d" % i, "output_%d_price" % i]
cols += [
    "revenue", "input_bill", "energy_cost", "maintenance", "labour_cost", "net_standalone",
    "rate_unskilled", "rate_skilled", "rate_h_skilled", "grid_buy_price",
]

rows = []
for r in recipes:
    b = buildings.get(r.get("building_id", ""), {})
    # 49 recipes name a building that has no row in the MVP buildings CSV — they sit behind
    # the catalog's silent promotion gate and can never be built or costed. Mark them rather
    # than emitting a 0 maintenance that would read as "free to run".
    buildable = bool(b)
    row = {
        "recipe_id": r.get("recipe_id", ""),
        "display_name": r.get("display_name", ""),
        "building_id": r.get("building_id", ""),
        "building_display": b.get("display_name", ""),
        "category": r.get("category", ""),
        "required_research": r.get("required_research", ""),
        "catalysts": r.get("catalysts", ""),
        "buildable": "TRUE" if buildable else "FALSE",
        "maintenance_cost": b.get("maintenance_cost", ""),
        "energy_req": r.get("energy_req", ""),
        "rate_unskilled": RATE_U, "rate_skilled": RATE_S, "rate_h_skilled": RATE_H,
        "grid_buy_price": GRID_BUY,
    }
    u, src = headcount(r, b, "labour_unskilled_required")
    s, _ = headcount(r, b, "labour_skilled_required")
    h, _ = headcount(r, b, "labour_h_skilled_required")
    row["labour_unskilled"], row["labour_skilled"], row["labour_h_skilled"] = u, s, h
    row["labour_source"] = src

    input_bill = 0.0
    for i in range(1, MAX_IN + 1):
        name = (r.get("input_%d" % i) or "").strip()
        qty = (r.get("qty_%d" % i) or "").strip()
        row["input_%d" % i] = name
        row["qty_%d" % i] = qty
        row["input_%d_price" % i] = "%.6g" % price(name) if name else ""
        if name and qty:
            input_bill += price(name) * int(qty)

    revenue = 0.0
    for i in range(1, MAX_OUT + 1):
        name = (r.get("output_%d" % i) or "").strip()
        qty = (r.get("output_qty_%d" % i) or "").strip()
        row["output_%d" % i] = name
        row["output_qty_%d" % i] = qty
        row["output_%d_price" % i] = "%.6g" % price(name) if name else ""
        if name and qty:
            revenue += price(name) * int(qty)

    energy_cost = float(r.get("energy_req") or 0) * GRID_BUY
    maintenance = float(b.get("maintenance_cost") or 0)
    labour_cost = u * RATE_U + s * RATE_S + h * RATE_H
    row["revenue"] = "%.4f" % revenue
    row["input_bill"] = "%.4f" % input_bill
    row["energy_cost"] = "%.4f" % energy_cost
    # Costs and net are only meaningful for a recipe whose building exists.
    row["maintenance"] = "%.4f" % maintenance if buildable else ""
    row["labour_cost"] = "%.4f" % labour_cost
    row["net_standalone"] = "%.4f" % (revenue - input_bill - energy_cost - maintenance - labour_cost) if buildable else ""
    rows.append(row)

OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=cols)
    w.writeheader()
    w.writerows(rows)

print("wrote %s" % OUT.relative_to(ROOT))
print("  %d recipes x %d columns" % (len(rows), len(cols)))
print("  rates recorded: unskilled %.5f skilled %.5f h_skilled %.5f grid_buy %.2f"
      % (RATE_U, RATE_S, RATE_H, GRID_BUY))
by_building = {}
for r in rows:
    by_building.setdefault(r["building_id"], set()).add(r["maintenance_cost"])
bad = {k: v for k, v in by_building.items() if len(v) > 1}
print("  maintenance is consistent within every building: %s"
      % ("YES" if not bad else "NO -> %s" % bad))
n_unbuildable = sum(1 for r in rows if r["buildable"] == "FALSE")
print("  buildable: %d   NOT buildable (no such building in the MVP catalog): %d"
      % (len(rows) - n_unbuildable, n_unbuildable))
